### ISSUE TITLE
resource selector should not create URLs with spaces

### ISSUE THREAD

**Issue by seebi** [AKSW/RDFauthor#15]
please see https://github.com/AKSW/OntoWiki/issues/144

**Comment by frodeseverin** [comment]
Or other invalid characters for an URL for that matter.

**Comment by seebi** [comment]
@cannelony : There should be a URI encoding function in javascript, right?

**Comment by seebi** [comment]
http://www.w3schools.com/jsref/jsref_encodeuri.asp

**Comment by cannelony** [comment]
http://www.w3schools.com/jsref/jsref_encodeuricomponent.asp

**Comment by frodeseverin** [comment]
Thank you for looking into this issue.

However, this was but a partial fix. Have a look at 
http://data.bbib.no/view/r/Nordahl_Grieg 
for a demonstration.

The source for the resource is correct now, although not very readable. Readability is an Erfurt issue, and I will report it there.

```
<Nordahl_Grieg> <frbr:creatorOf> <Til_Ungdommen> ;
                frbr:creatorOf <http://data.bbib.no/data/17._mai_1914>, <http://data.bbib.no/data/Ung%20m%C3%A5%20verden%20ennu%20v%C3%A6re>, <http://data.bbib.no/data/Ung%20m%C3%A5%20verden%20ennu%20v%C3%A6re%20%3A%20roman>, <http://data.bbib.no/data/V%C3%A5r%20%C3%A6re%20og%20v%C3%A5r%20makt> ;
                whois:stage <Nordahl_Grieg_birth>, <Nordahl_Grieg_death> ;
                a foaf:Person ;
                rdfs:label "Nordahl Grieg" ;
                owl:sameAs <http://dbpedia.org/resource/Nordahl_Grieg> ;
                skos:hiddenLabel "Nordahl Grieg" ;
                foaf:familyName "Grieg" ;
                foaf:givenName "Nordahl" ;
                foaf:name "Nordahl Grieg" .
```

However, I had a hard time using OntoWiki to achieve this.

The entry 
http://data.bbib.no/data/V%C3%A5r%20%C3%A6re%20og%20v%C3%A5r%20makt  
and 
http://data.bbib.no/data/Ung%20m%C3%A5%20verden%20ennu%20v%C3%A6re 
was correctly converted to a proper URL by RDFAuthor. The entry 
http://data.bbib.no/data/Ung%20m%C3%A5%20verden%20ennu%20v%C3%A6re%20%3A%20roman 
was not. I suppose this is due to the inclusion of the character sequence " : ". 

To create this link, I used the service at http://meyerweb.com/eric/tools/dencoder/ to encode the string "http://data.bbib.no/data/Ung må verden ennu være : roman", and pasted the encoded string into the add property widget in OntoWiki.

Since OntoWiki does not play well with urlencoded URI's in the first place, as reported in AKSW/OntoWiki#145, I then had to paste the urlencoded URI into the `View Resource` box of OntoWiki in order to specify a label for the resource.

The label is now visible in the OntoWiki interface at 
http://data.bbib.no/view/r/Nordahl_Grieg

;)Frode

**Comment by frodeseverin** [comment]
Interestingly, links to exsternal IRI's seems to be handled differently, albeit still wrong.

See https://github.com/AKSW/OntoWiki/issues/145#issuecomment-9375027 again for a description. Possibly the two previos posts there should have been made in this issue here. Sorry.
