### ISSUE TITLE
tests/gui-tests don't work out-of-the box

### ISSUE THREAD

**Issue by tfrancart** [AKSW/RDFauthor#17]
I started from tests/gui-test/vcard.html

var RDFAUTHOR_BASE = 'http://localhost/rdfauthor';

should be replaced by

var RDFAUTHOR_BASE = document.location.href.replace('vcard.html', '../..');

Then I changed the url of the sparql endpoint to be an empty SPARQL1.1 compatible Sesame server locally running on my machine.

When loading the page, I get the rdfauthor popup, displaying only the 3 buttons "Add property", "Save" and "Cancel". Clicking on "Add property" freezes the page and does nothing.
How can I get a running example of RDFAuthor with a local HTML page and a local SPARQL endpoint ?

Sorry to file this as an issue but I couldn't find another way to reach you.
Thanks

**Comment by cannelony** [comment]
Hi,
i extended the [vcard.html](https://github.com/AKSW/RDFauthor/blob/develop/tests/gui-tests/vcard.html). Maybe that helps.
1. set RDFAUTHOR_BASE
2. set queryEndpoint and updateEndpoint
   
   `<link about="http://localhost/rdfauthor/test/" rel="update:queryEndpoint" href="http://localhost/sparql" />` 
   `<link about="http://localhost/rdfauthor/test/" rel="update:updateEndpoint" href="http://localhost/sparql" />`
   
   In my case the queryEndpoint and updateEnpoint was an virtuoso sparql endpoint.
3. specify which resource you want to edit
   
   If your local HTML page has more than one resource you can specify which resource you want to edit by using
   
   `RDFauthor.start(JQUERYSELECTOR)`
   
   otherwise RDFauthor loads the first read resource.

Regards.

**Comment by seebi** [comment]
Hi tfrancart, writing issues is just fine :-)

does clemens activity solves your problem?
